png(file="plot4.png")
par(mfrow =c(2,2),mar=c(4,4,2,1))
plot(datsub$Datetime,datsub$Global_active_power,type="l",xlab="",ylab="Global_active_power(kilowatts)")
plot(datsub$Datetime,datsub$Voltage,xlab="datetime",ylab="Voltage",type="l")
with(datsub,plot(Datetime,Sub_metering_1,xlab="",ylab="Energy sub metering",type="n"))
with(datsub,points(Datetime,Sub_metering_1,type="l"))
with(datsub,points(Datetime,Sub_metering_2,type="l",col="blue"))
with(datsub,points(Datetime,Sub_metering_3,type="l",col="red"))
legend("topright",lty=1,col=c("black","red","blue"),legend=c("submetering_1","submetering_2","submetering_3"))
plot(datsub$Datetime,datsub$Global_reactive_power,xlab="datetime",ylab="Global_active_power",type="h")
dev.off() 